# Generated by Django 3.0.1 on 2020-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messag',
            name='vu',
            field=models.BooleanField(default=False),
        ),
    ]
